version: "3.3"
services:
  web:
    image: moodlehq/moodle-php-apache:7.4 
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/moodledata
  db:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin4567!
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: admin_moodle_1234
